#!/bin/sh
#
# Start the network....
#



case "$1" in
  start)
	FILE=/test_plan/wifi/auto_reboot_all
	if [ -f  ${FILE} ]
	then
		read -t 3 BREAK_FLAG
		if [ $? -eq 0 ]
		then
			rm ${FILE}
			sync
			exit 0
		else
		    sh /test_plan/wifi/wifi_test.sh
		fi
		[ $? = 0 ] && echo "OK" || echo "FAIL"
	fi
	;;
  stop)
	echo "stop wifi test."
	[ $? = 0 ] && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

