#!/bin/sh
# devtmpfs does not get automounted for initramfs
/bin/mount -t devtmpfs devtmpfs /dev

if echo "/dev/console is OK" > /dev/console;then
	exec 0</dev/console
	exec 1>/dev/console
	exec 2>/dev/console
fi

exec /sbin/init "$@"
