#!/bin/sh

export HDR_MODE=1
#vi_aging adjust
io -4 0xfe801048 0x10

case "$1" in
  start)
    ispserver -no-sync-db &
    ;;
  stop)
    killall ispserver
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
