#!/bin/sh
#

soc_configure()
{
	#vpu 600M
	echo 600 >/sys/kernel/debug/mpp_service/rkvenc/clk_core

	#cpu x2
	echo 0 > /sys/devices/system/cpu/cpu2/online
	echo 0 > /sys/devices/system/cpu/cpu3/online

	#npu 600M
	echo userspace > /sys/devices/platform/ffbc0000.npu/devfreq/ffbc0000.npu/governor
	echo 600000000 > /sys/devices/platform/ffbc0000.npu/devfreq/ffbc0000.npu/userspace/set_freq
}

lunch_start()
{
	#soc_configure
	sh /etc/preinit.d/ispp_init.sh
	echo "Now we are ready to start your first application"
	mediaserver -d -a -c /etc/mediaserver_tiny.conf
}

lunch_stop()
{
	killall mediaserver
	echo "All applications have been stopped"
}

case "$1" in
	start)
		lunch_start
		;;
	stop)
		lunch_stop
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
