#!/bin/sh
#
# Start 3A daemon for each /dev/mediaX device
#

case "$1" in
  start)
      start-stop-daemon -S -m -b -p /tmp/.rkaiq_3A --startas \
        /bin/sh -- -c "/oem/usr/bin/rkaiq_3A_server --mmedia=/dev/media0 -w 2688 -h 1520 -t 0 2>&1 | logger -t rkaiq_3A"
    ;;
  stop)
    killall rkaiq_3A_server
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
