UPDATER_SITE = $(TOPDIR)/../app/updater
UPDATER_SITE_METHOD = local
UPDATER_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_UPDATER_FOR_EMMC),y)
    UPDATER_CONF_OPTS += -DUSE_EMMC=1
endif
ifeq ($(BR2_PACKAGE_UPDATER_FOR_NOR),y)
    UPDATER_CONF_OPTS += -DUSE_NOR=1
endif

$(eval $(cmake-package))
