#!/bin/sh

NAME1=bsa_server
DAEMON1=/usr/bin/$NAME1
PIDFILE1=/var/run/$NAME1.pid

NAME2=app_manager
DAEMON2=/usr/bin/$NAME2
PIDFILE2=/var/run/$NAME2.pid

NAME3=app_avk
DAEMON3=/usr/bin/$NAME3
PIDFILE3=/var/run/$NAME3.pid

hcd_file="/system/etc/firmware/BCM4345C0.hcd"
echo "hcd_file = $hcd_file"

case "$1" in
    start)

    echo 0 > /sys/class/rfkill/rfkill0/state
    sleep 1
    echo 1 > /sys/class/rfkill/rfkill0/state
    sleep 1

    mkdir /data/bsa 2>/dev/null
    mkdir /data/bsa/config 2>/dev/null
    cd /data/bsa/config
    echo "start broadcom bluetooth server bsa_sever"
    start-stop-daemon -S  -m -p $PIDFILE1 -x $DAEMON1 -- -r 13 -all=0 -b /data/btsnoop.log -p $hcd_file -d /dev/ttyS4 > /data/bsa/bsa_log &
    sleep 2

    echo "start broadcom bluetooth app_manager"
    start-stop-daemon -S  -m -p $PIDFILE2 -x $DAEMON2 -- -s &

    echo "start broadcom bluetooth app_avk"
    start-stop-daemon -S  -m -p $PIDFILE3 -x $DAEMON3 -- -s &
    sleep 1


    echo "#########act as a bluetooth music player#########"
    app_socket avk 2
    cd - > /dev/null
    sleep 2
    echo "


|-----bluetooth music player is ready for connections------|"

        ;;
    stop)
        echo -n "Stopping broadcom bluetooth server & app"
        app_socket avk 99
        app_socket manager 99
        sleep 1
        start-stop-daemon -K -o -p $PIDFILE1
        sleep 2
        rm -f $PIDFILE1
        rm -f $PIDFILE2
        rm -f $PIDFILE3
        sleep 2
        echo 0 > /sys/class/rfkill/rfkill0/state
        echo "


|-----bluetooth music player is shutdown-----|"

        ;;
    *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac

exit $?

