#!/bin/sh
backup=/dev/block/by-name/backup
file=/tmp/tmp_mac
NETINTERFACE=eth0
IP="172.16.110.2"
GW="172.16.110.1"

case "$1" in
  start)
    # rndis Mac 地址写入 backup 分区，开机校验分区是否存在 Mac 地址
    dd if=$backup of=$file bs=100 count=1
    MAC=$(cat $file  | cut -c1-50 | grep FFMAC | awk -F '=' '{print $2}')
    if [ ! -n "$MAC" ];then
	    MAC=$(ip link show $NETINTERFACE |  grep ether | awk -F ' ' '{print $2}')
	    echo "FFMAC=$MAC" > $file
	    dd if=$file of=$backup
    fi

    ifconfig $NETINTERFACE down
    ifconfig $NETINTERFACE hw ether $MAC

    ifconfig $NETINTERFACE $IP
    ifconfig $NETINTERFACE down
    ifconfig $NETINTERFACE up
    route add default gw $GW
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
