#!/bin/sh

case "$1" in
  start)
    ifconfig eth0 172.16.110.2
    ifconfig eth0 down
    ifconfig eth0 up
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0

