#!/bin/sh
#

case "$1" in
	start)
		{
			insmod /usr/lib/modules/4.19.111/kernel/drivers/mmc/host/dw_mmc-rockchip.ko
			insmod /usr/lib/modules/4.19.111/kernel/drivers/net/wireless/rockchip_wlan/rkwifi/bcmdhd_indep_power/bcmdhd.ko
		}&
		;;
	stop)
		dhd_priv setsuspendmode 1
		;;
	*)
		echo "Usage: $0 {start|stop}"
		exit 1
		;;
esac

exit 0
