LIBIPCPROTOCOL_SITE = $(TOPDIR)/../app/libIPCProtocol
LIBIPCPROTOCOL_SITE_METHOD = local

LIBIPCPROTOCOL_INSTALL_STAGING = YES

LIBIPCPROTOCOL_DEPENDENCIES = libgdbus librkdb

$(eval $(cmake-package))
