#!/bin/sh
#chkconfig:2345 80 90
#description:auto ddr window test
#sleep 8 sec waiting for system ready

function start_ddrwin()
{
	###############################
	echo "ddr window test start..."
	###############################
	DDR_WINDOW_DIR=/test_plan/ddr/ddr_window
	kernel_version=$(uname -a | awk '{print $3}')
	ddr_window_path=/lib/modules/${kernel_version}/kernel/drivers/amlogic/ddr_window/ddr_window.ko
	echo "kernel: ${kernel_version}"
	
	echo "ddr window path: ${ddr_window_path}"
	insmod ${ddr_window_path}
	if [ $? -ne 0 ]
	then
		echo "insmod ddr_window.ko failure"
		exit 1
	fi
	${DDR_WINDOW_DIR}/memcpy_test -f &
	if [ $? -ne 0 ]
	then
		echo "FAILURE: memcpy_test aplication start error."
		exit 1
	fi
	${DDR_WINDOW_DIR}/ddr_window -f &
	if [ $? -ne 0 ]
	then
		echo "FAILURE: ddr window aplication start error."
		exit 1
	fi
}

case "$1" in
start)
    sleep 5
	start_ddrwin
    ;;
esac

exit $?
