#!/bin/sh
#
# Insmod
#
case "$1" in
  start)
        /usr/bin/recovery
        ;;
  stop)
        printf "stop finished\n"
        ;;
  *)
        echo "Usage: $0 {start|stop}"
        exit 1
        ;;
esac
exit 0
