RV1108_UVC_APP_SITE = $(TOPDIR)/../app/uvc_app
RV1108_UVC_APP_SITE_METHOD = local
RV1108_UVC_APP_INSTALL_STAGING = YES

# add dependencies
RV1108_UVC_APP_DEPENDENCIES = libcamerahal librkfb librkrga mpp librkuvc

RV1108_UVC_APP_CONF_OPTS += -DISP_FMT=$(call qstrip,$(BR2_PACKAGE_RV1108_UVC_APP_ISP_FORMAT))
RV1108_UVC_APP_CONF_OPTS += -DCIF_FMT=$(call qstrip,$(BR2_PACKAGE_RV1108_UVC_APP_CIF_FORMAT))
RV1108_UVC_APP_CONF_OPTS += -DISP_SEQ=$(BR2_PACKAGE_LIBRKUVC_ISP_TO_UVC_SEQ)
RV1108_UVC_APP_CONF_OPTS += -DCIF_SEQ=$(BR2_PACKAGE_LIBRKUVC_CIF_TO_UVC_SEQ)
ifeq ($(BR2_PACKAGE_ADBD),y)
    RV1108_UVC_APP_CONF_OPTS += -DUSE_ADB=1
endif

$(eval $(cmake-package))
