LOCK_SITE = $(TOPDIR)/../app/lock
LOCK_SITE_METHOD = local
LOCK_INSTALL_STAGING = YES

# add dependencies
LOCK_DEPENDENCIES = libcamerahal librkfb librkrga

COMPILE_PROJECT_TYPE=$(call qstrip,$(RV_TARGET_LOCK_PROJECT_TYPE))
COMPILE_UI_TRUETYPE=$(call qstrip,$(BR2_PACKAGE_FREETYPE))
COMPILE_UI_TSLIB=$(call qstrip,$(BR2_PACKAGE_TSLIB))

LOCK_DEPENDENCIES += rv1108_libpng rv1108_minigui
ifeq ($(COMPILE_UI_TRUETYPE), y)
LOCK_DEPENDENCIES += freetype
LOCK_CONF_OPTS += -DCOMPILE_UI_TRUETYPE=$(COMPILE_UI_TRUETYPE)
endif

ifeq ($(COMPILE_UI_TSLIB), y)
LOCK_DEPENDENCIES += tslib
LOCK_CONF_OPTS += -DCOMPILE_UI_TSLIB=$(COMPILE_UI_TSLIB)
endif

ifeq ($(BR2_PACKAGE_SQLITE),y)
    LOCK_DEPENDENCIES += sqlite
    LOCK_CONF_OPTS += -DUSE_SQLITE=y
endif

ifeq ($(BR2_PACKAGE_DATABASE),y)
    LOCK_DEPENDENCIES += database
    LOCK_CONF_OPTS += -DUSE_DATABASE=y
endif

ifeq ($(RV_TARGET_LOCK_ENABLE_DISP_HOLD),y)
    LOCK_CONF_OPTS += -DENABLE_DISP_HOLD=1
endif

RV_BOARD_VERSION = rv1108-lock-evb-v10
RV_LCD_RESOLUTION = "360x640"

LOCK_CONF_OPTS += -DCOMPILE_PROJECT_TYPE=$(RV_TARGET_LOCK_PROJECT_TYPE)
LOCK_CONF_OPTS += -DCOMPILE_BOARD_VERSION=$(RV_BOARD_VERSION)
LOCK_CONF_OPTS += -DResolution=$(call qstrip,$(RV_LCD_RESOLUTION))

LOCK_CONF_OPTS += \
    -DMAIN_APP_PRE_FACE_ROTATE=$(RV_TARGET_MAIN_APP_PRE_FACE_ROTATE) \
    -DMAX_FEATURE_OF_USER=$(RV_TARGET_MAX_FEATURE_OF_USER) 

LOCK_CONFIGURE_DEP_CONFIGS = RV_TARGET_LOCK_PROJECT_TYPE \
	RV_LCD_RESOLUTION \
	RV_BOARD_VERSION

$(eval $(cmake-package))
