ROCKX_SITE = $(TOPDIR)/../external/rockx
ROCKX_SITE_METHOD = local

ROCKX_INSTALL_STAGING = YES

ifeq ($(BR2_PACKAGE_RK1806),y)
ROCKX_COMPILE_PLATFORM = rk1806
endif

ifeq ($(BR2_PACKAGE_RK1808),y)
ROCKX_COMPILE_PLATFORM = rk1808
endif

ifeq ($(BR2_PACKAGE_RK3399PRO),y)
ROCKX_COMPILE_PLATFORM = rk3399pro
endif

ifeq ($(BR2_PACKAGE_RV1126_RV1109),y)
ROCKX_COMPILE_PLATFORM = rv1109
endif

ROCKX_CONF_OPTS = -DCOMPILE_PLATFORM=$(ROCKX_COMPILE_PLATFORM)-Linux

$(eval $(cmake-package))
