RKADK_SITE = $(TOPDIR)/../external/rkadk
RKADK_SITE_METHOD = local
RKADK_INSTALL_STAGING = YES

RKADK_DEPENDENCIES += rkmedia

ifeq ($(BR2_PACKAGE_RKMEDIA_USE_AIQ), y)
RKADK_DEPENDENCIES += camera_engine_rkaiq
RKADK_CONF_OPTS += -DUSE_RKAIQ=ON
endif

RKADK_RKMEDIA_INCLUDE = $(TOPDIR)/../external/rkmedia/include/rkmedia

RKADK_CONF_OPTS += -DCMAKE_C_FLAGS="-I$(RKADK_RKMEDIA_INCLUDE)" -DCMAKE_CXX_FLAGS="-I$(RKADK_RKMEDIA_INCLUDE)"

RKADK_CONF_OPTS += -DCMAKE_INSTALL_STAGING=$(STAGING_DIR)

$(eval $(cmake-package))
