#!/bin/sh
#
# Do BT initialzation for Rockchip Linux SDK....
#

case "$1" in
start)
	echo "Welcome to Rockchip Linux for BT"
	# bluetooth
	rkbt  /etc/bluetooth/bcm4354a1.hcd /dev/ttyS0 &
	;;
stop)
	printf "stop finished"
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
