#!/bin/sh
#
# Do BT initialzation for Rockchip Linux SDK....
#

case "$1" in
start)
	echo "Welcome to Rockchip Linux for BT"
	# Power on wifi/bt if exist
        echo 1 >  /sys/class/rfkill/rfkill0/state || true

        # bluetooth
        rkbt /etc/bluetooth/bcm43438a0.hcd /dev/ttyS1 &

	#alsa conf
        CARD=rk809
        ALSA_CARD_NAME=rockchip_rk809-
        sed -i "4a${ALSA_CARD_NAME} cards.${CARD}" /usr/share/alsa/cards/aliases.conf
	;;
stop)
	printf "stop finished"
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
