#!/bin/sh
#
# setup configfs for ntbd and usb mass storage....
#

case "$1" in
start)
	mkdir /dev/usb-ffs -m 0770
	mkdir /dev/usb-ffs/ntb -m 0770
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/rockchip  -m 0770
	echo 0x2207 > /sys/kernel/config/usb_gadget/rockchip/idVendor
	# ADD_IDPRODUCT
	echo 0x1808 > /sys/kernel/config/usb_gadget/rockchip/idProduct
	mkdir /sys/kernel/config/usb_gadget/rockchip/strings/0x409   -m 0770
	echo "0123456789ABCDEF" > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/serialnumber
	echo "rockchip"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/manufacturer
	echo "rk3xxx"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/product
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1  -m 0770
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1/strings/0x409  -m 0770
	echo 500 > /sys/kernel/config/usb_gadget/rockchip/configs/b.1/MaxPower

	# INIT_FUNCTIONS
	mkdir /sys/kernel/config/usb_gadget/rockchip/functions/ffs.ntb
	ln -s /sys/kernel/config/usb_gadget/rockchip/functions/ffs.ntb /sys/kernel/config/usb_gadget/rockchip/configs/b.1/f1	

	# INIT_CONFIG
	echo "ntb" > /sys/kernel/config/usb_gadget/rockchip/configs/b.1/strings/0x409/configuration

	# START_APP_BEFORE_UDC
	mkdir -p /dev/usb-ffs/ntb
	mount -o uid=2000,gid=2000 -t functionfs ntb /dev/usb-ffs/ntb
	export service_ntb_tcp_port=5555

	#UDC=`ls /sys/class/udc/| awk '{print $1}'`
	#echo $UDC > /sys/kernel/config/usb_gadget/rockchip/UDC
	# START_APP_AFTER_UDC

	;;
stop)
	echo "none" > /sys/kernel/config/usb_gadget/rockchip/UDC
	;;
restart|reload)
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
