#!/bin/sh
#
# setup configfs for adbd and usb mass storage....
#

case "$1" in
start)
	mkdir /dev/usb-ffs -m 0770
	mkdir /dev/usb-ffs/adb -m 0770
	mount -t configfs none /sys/kernel/config
	mkdir /sys/kernel/config/usb_gadget/rockchip  -m 0770
	echo 0x2207 > /sys/kernel/config/usb_gadget/rockchip/idVendor
	# ADD_IDPRODUCT
	mkdir /sys/kernel/config/usb_gadget/rockchip/strings/0x409   -m 0770
	echo "0123456789ABCDEF" > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/serialnumber
	echo "rockchip"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/manufacturer
	echo "rk3xxx"  > /sys/kernel/config/usb_gadget/rockchip/strings/0x409/product
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1  -m 0770              
	mkdir /sys/kernel/config/usb_gadget/rockchip/configs/b.1/strings/0x409  -m 0770
	echo 500 > /sys/kernel/config/usb_gadget/rockchip/configs/b.1/MaxPower

	# INIT_FUNCTIONS

	# INIT_CONFIG

	# START_APP_BEFORE_UDC
	UDC=`ls /sys/class/udc/| awk '{print $1}'`
	echo $UDC > /sys/kernel/config/usb_gadget/rockchip/UDC
	# START_APP_AFTER_UDC

	;;
stop)
	echo "none" > /sys/kernel/config/usb_gadget/rockchip/UDC
	;;
restart|reload)
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit 0
