#!/bin/sh
#
# check if we need to resize or format oem and userdata partition....
#

case "$1" in
start)
	mount -a 2>/dev/null
	if [ -f /etc/init.d/S40_recovery ]
	then
		echo "we are in recovery, skip init oem/userdata"
	else
		echo "we are in rootfs, init oem/userdata"
		partinit oem
		partinit userdata
	fi
	;;
stop)
	;;
*)
	echo "Usage: $0 {start|stop}"
	exit 1
esac

exit 0
