#!/bin/sh
backup=/dev/block/by-name/backup
file=/tmp/tmp_mac

case "$1" in
  start)
 	dd if=$backup of=$file bs=100 count=1
    ;;
  stop)
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
