STORAGE_MANAGER_SITE = $(TOPDIR)/../app/storage_manager
STORAGE_MANAGER_SITE_METHOD = local

STORAGE_MANAGER_DEPENDENCIES = libgdbus librkdb

ifeq ($(BR2_PACKAGE_RK_OEM), y)
STORAGE_MANAGER_INSTALL_TARGET_OPTS = DESTDIR=$(BR2_PACKAGE_RK_OEM_INSTALL_TARGET_DIR) install/fast
STORAGE_MANAGER_DEPENDENCIES += rk_oem
endif

$(eval $(cmake-package))
