PEEPHOLE_SITE = $(TOPDIR)/../app/peephole
PEEPHOLE_SITE_METHOD = local
PEEPHOLE_INSTALL_STAGING = YES

# add dependencies
PEEPHOLE_DEPENDENCIES = librkfb librkrga

COMPILE_PROJECT_TYPE=$(call qstrip,$(RV_TARGET_LOCK_PROJECT_TYPE))
COMPILE_UI_TRUETYPE=$(call qstrip,$(BR2_PACKAGE_FREETYPE))
COMPILE_UI_TSLIB=$(call qstrip,$(BR2_PACKAGE_TSLIB))


#ifeq ($(filter NO_DISP,$(COMPILE_PROJECT_TYPE)),)
PEEPHOLE_DEPENDENCIES += rv1108_libpng rv1108_minigui
ifeq ($(COMPILE_UI_TRUETYPE), y)
	PEEPHOLE_DEPENDENCIES += freetype
	PEEPHOLE_CONF_OPTS += -DCOMPILE_UI_TRUETYPE=y
endif
ifeq ($(COMPILE_UI_TSLIB), y)
	PEEPHOLE_DEPENDENCIES += tslib
	PEEPHOLE_CONF_OPTS += -DCOMPILE_UI_TSLIB=y
endif
#endif

ifeq ($(RV_TARGET_SQLITE),y)
	PEEPHOLE_DEPENDENCIES += sqlite
	PEEPHOLE_CONF_OPTS += -DUSE_SQLITE=y
endif

ifeq ($(RV_TARGET_DATABASE),y)
	PEEPHOLE_DEPENDENCIES += database
	PEEPHOLE_CONF_OPTS += -DUSE_DATABASE=y
endif

PEEPHOLE_CONF_OPTS += -DCOMPILE_PROJECT_TYPE=$(RV_TARGET_LOCK_PROJECT_TYPE)
PEEPHOLE_CONF_OPTS += -DCOMPILE_BOARD_VERSION=$(RV_BOARD_VERSION)
PEEPHOLE_CONF_OPTS += -DResolution=$(call qstrip,$(RV_LCD_RESOLUTION))

PEEPHOLE_CONFIGURE_DEP_CONFIGS = RV_TARGET_LOCK_PROJECT_TYPE \
	RV_LCD_RESOLUTION \
	RV_BOARD_VERSION


$(eval $(cmake-package))
