#!/bin/sh
#
# Start mount /data....
#

case "$1" in
  start)
	[ ! -d /data ] && mkdir /data
	[ -r /dev/mmcblk0p8 ] && /bin/busybox mount -t ext4 /dev/mmcblk0p5 /data
	[ -r /dev/mtdblock5 ] && /bin/busybox mount -t jffs2 /dev/mtdblock5 /data
	str_value=`/bin/busybox df | grep /data`
        [ ! -z "$str_value" ] && echo "/data mount success" || echo "/data mount fail"
	;;
  stop)
	umount /data
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
