FACE_SERVICE_SITE = $(TOPDIR)/../app/face
FACE_SERVICE_SITE_METHOD = local
FACE_SERVICE_INSTALL_STAGING = YES

# add dependencies
FACE_SERVICE_DEPENDENCIES = hal adk messenger librkrga librkfb messenger adk libcamerahal rkcamera


ifeq ($(BR2_PACKAGE_MODEL_LOADER),y)
    FACE_SERVICE_DEPENDENCIES += model_loader
    FACE_SERVICE_CONF_OPTS += -DUSE_MODEL_LOAD=1
endif

ifeq ($(BR2_PACKAGE_SQLITE),y)
    FACE_SERVICE_DEPENDENCIES += sqlite
    FACE_SERVICE_CONF_OPTS += -DUSE_SQLITE=1
endif

ifeq ($(RV_TARGET_FACE_USE_UVC),y)
    FACE_SERVICE_DEPENDENCIES += mpp librkuvc
    FACE_SERVICE_CONF_OPTS += -DUSE_UVC=1
endif

ifeq ($(RV_TARGET_FACE_USE_MJPEG_CAMERA),y)
    FACE_SERVICE_DEPENDENCIES += mpp
    FACE_SERVICE_CONF_OPTS += -DUSE_MJPEG_CAMERA=1
endif

ifeq ($(BR2_PACKAGE_DATABASE),y)
    FACE_SERVICE_DEPENDENCIES += database
    FACE_SERVICE_CONF_OPTS += -DUSE_DATABASE=1
endif

ifeq ($(RV_TARGET_RKFACE_DETECTION),y)
    FACE_SERVICE_DEPENDENCIES += rkface
    FACE_SERVICE_CONF_OPTS += -DUSE_RKFACE_DETECT=1
    FACE_SERVICE_CONF_OPTS += -DDOWNSCALE_WIDTH=$(RV_TARGET_FACE_DETECT_WIDTH)
    FACE_SERVICE_CONF_OPTS += -DDOWNSCALE_HEIGHT=$(RV_TARGET_FACE_DETECT_HEIGHT)
endif

ifeq ($(RV_TARGET_RKFACE_RECOGNITION),y)
    FACE_SERVICE_DEPENDENCIES += rkface
    FACE_SERVICE_CONF_OPTS += -DUSE_RKFACE_RECOGNIZE=1
endif

ifeq ($(RV_TARGET_RKLIVING_DETECTION),y)
    FACE_SERVICE_DEPENDENCIES += rkface
    FACE_SERVICE_CONF_OPTS += -DUSE_RKLIVE_DETECT=1
endif

ifeq ($(RV_TARGET_FACE_CAPTURE),y)
    FACE_SERVICE_DEPENDENCIES += rkmedia
    FACE_SERVICE_CONF_OPTS += -DUSE_FACE_CAPTURE=1
endif

ifeq ($(RV_TARGET_ENCODE_H264),y)
    FACE_SERVICE_DEPENDENCIES += rkmedia
    FACE_SERVICE_CONF_OPTS += -DUSE_H264_ENCODER=1
endif

ifeq ($(RV_TARGET_3D_LIVE_DETECTION),y)
    FACE_SERVICE_CONF_OPTS += -DUSE_3D_LIVE_DETECTION=1
    FACE_SERVICE_CONF_OPTS += -DDEPTH_WIDTH=$(RV_TARGET_DEPTH_WIDTH)
    FACE_SERVICE_CONF_OPTS += -DDEPTH_HEIGHT=$(RV_TARGET_DEPTH_HEIGHT)
endif

ifeq ($(BR2_PACKAGE_RV1108_VENDOR_STORAGE),y)
    FACE_SERVICE_DEPENDENCIES += vendor_storage
    FACE_SERVICE_CONF_OPTS += -DUSE_VENDOR_STORAGE=1
endif

FACE_SERVICE_CONF_OPTS += \
    -DDISPLAY_RESOLUTION=$(call qstrip,$(RV_LCD_RESOLUTION)) \
    -DMAIN_APP_PRE_FACE_ROTATE=$(RV_TARGET_MAIN_APP_PRE_FACE_ROTATE) \
    -DMAX_FEATURE_OF_USER=$(RV_TARGET_MAX_FEATURE_OF_USER) \
    -DBOARD_VERSION=$(RV_BOARD_VERSION)

$(eval $(cmake-package))
