LIBRKUVC_SITE = $(TOPDIR)/../framework/librkuvc
LIBRKUVC_SITE_METHOD = local
LIBRKUVC_INSTALL_STAGING = YES

# add dependencies
LIBRKUVC_DEPENDENCIES = sqlite mpp

LIBRKUVC_CONF_OPTS = -DUVC_FORMAT_FILE=$(call qstrip,$(BR2_PACKAGE_LIBRKUVC_FORMAT_FILE))
ifeq ($(BR2_PACKAGE_LIBRKUVC_YUYV_AS_RAW),y)
    LIBRKUVC_CONF_OPTS += -DYUYV_AS_RAW=1
endif
ifeq ($(BR2_PACKAGE_LIBRKUVC_CONFIG_UVC_RGA),y)
    LIBRKUVC_CONF_OPTS += -DCONFIG_UVC_RGA=1
endif
LIBRKUVC_CONF_OPTS += -DUSB_UVC_FUNCTION=$(call qstrip,$(BR2_PACKAGE_LIBRKUVC_USB_UVC_FUNCTION))

$(eval $(cmake-package))
